export const menu2 = {
  options: ['Sushi', 'White Castle', 'Other'],
  Sushi: [
    'Kappa Roll',
    'Oshinko Roll',
    'Kanpyo Roll',
    'Tamago Roll',
    'Tuna Roll',
    'Salmon Roll',
    'Negi Toro Roll',
    'Negi Hama Roll',
    'Wild Salmon Roll',
    'California Roll',
    'BC Roll',
    'Inari Roll',
    'Avocado Roll',
    'Gomae Roll',
    'Spicy Tuna Roll',
    'Spicy Salmon Roll',
    'Tuna and Avocado Roll',
    'Salmon and Avocado Roll',
    'Vegetable Roll',
    'Yam Tempura Roll',
    'Vegetable Tempura Roll',
    'Asparagus Tempura Roll',
    'Wakame Roll',
    'Dynamite Roll',
    'Smoked Yam Roll',
    'Smoked Salmon Roll',
    'Beef Teriyaki Roll',
    'Chicken Teriyaki Roll',
    'Chopped Scallop Roll',
    'Alaska Roll',
    'Unagi Roll',
    'Ebi Roll',
    'Spicy Chopped Scallop Roll',
    'Futomaki',
    'Spicy Tuna Tempura Roll',
    'Spicy Salmon Tempura Roll',
    'Deep Fried California Roll',
    'Unagi Tempura Roll',
    'Deep Fried Roll',
  ],
  'White Castle': [
    'Shrimp Nibblers',
    'The Impossible Slider with Smoked Cheddar Cheese',
    'The Original Slider',
    'Cheese Slider',
    'Bacon Cheese Slider',
    'Double Cheese Slider',
    'Crispy Chicken Breast Slider',
    'Chicken Ring Slider',
    'Bacon and Cheddar Chicken Slider',
    'Veggie Slider',
    'Panko Breaded Fish Slider',
    'Breakfast Slider',
    'Original Slider with Egg and Cheese',
    'Breakfast Toast Sandwich',
    'Belgian Waffle Slider',
    'Chicken and Waffles Slider',
    'Hash Brown Nibblers',
    'Mini Belgian Waffles',
    'One Breakfast Slider Combo',
    'Two Breakfast Slider Combo',
    'Belgian Waffle Slider Combo',
    'One Breakfast Toast Sandwich Combo',
    'Two Breakfast Toast Sandiwches Combo',
    // 'The Original Slider Combo',
    // 'Double Cheese Slider Combo',
    // 'Chicken Breast Slider Combo',
    // 'TWO BREAKFAST TOAST SANDWICHES COMBO',
    // 'THE ORIGINAL SLIDER COMBO',
    // 'DOUBLE CHEESE SLIDER COMBO',
    // 'CHICKEN BREAST SLIDER COMBO',
    // 'FISH SLIDER COMBO',
    // 'CHICKEN RING COMBO',
    // 'CHICKEN RING SLIDER COMBO',
    // 'Crave Clutch',
    // "BUY 'EM BY THE SACK™",
    // 'CRAVE CASE',
    // 'CRAVE CRATE',
    // 'FRENCH FRIES',
    // 'LOADED FRIES',
    // 'ONION CHIPS/ONION RINGS',
    // 'MOZZARELLA CHEESE STICKS',
    // 'FISH NIBBLERS',
    // 'CHICKEN RINGS',
    // 'COLD DRINKS',
    // 'HOT DRINKS',
    // 'SHAKES',
    // 'MONSTER ENERGY DRINK',
    // 'MILK AND JUICE',
    // 'STRAWBERRY CHEESECAKE ON-A-STICK',
    // 'FUDGE DIPPED BROWNIE-ON-A-STICK',
    // 'GOOEY BUTTERCAKE-ON-A-STICK',
  ],
  Other: [
    'other',
    'chicken',
    'fish',
    'red meat',
    'pasta',
    'no',
    'duplicates',
    'allowed',
    'test',
  ],
};
